"""Initial Migration

Revision ID: 53a13d424093
Revises: 024c9d4b7496
Create Date: 2020-09-26 06:52:57.207090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a13d424093'
down_revision = '024c9d4b7496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_encrypt', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_encrypt')
    # ### end Alembic commands ###
